### ISSUE TITLE
Error while running your example

### ISSUE THREAD

**Issue by Emilianocm23** [taskiq-python/taskiq-redis#34]
Hello, im using the same code as the example here on your docs, and i get an error. 

Error:
```
taskiq_result: TaskiqResult[_ReturnType] = pickle.loads(result_value)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'NoneType'

The above exception was the direct cause of the following exception:

    raise ResultGetError() from exc
taskiq.exceptions.ResultGetError
```

Code:
```
import asyncio
from taskiq_redis import ListQueueBroker, RedisAsyncResultBackend

url = f'redis://default:passwordhere@myremoteserver.com:11131'

redis_async_result = RedisAsyncResultBackend(
    redis_url=url,
)
broker = ListQueueBroker(
    url=url,
    result_backend=redis_async_result,
)



@broker.task
async def best_task_ever() -> None:
    """Solve all problems in the world."""
    await asyncio.sleep(5.5)
    print("All problems are solved!")


async def main():
    task = await best_task_ever.kiq()
    print(await task.get_result())


asyncio.run(main())
```
I want to use the same redis database for tasks broker and results. (Like Django-Q)
Im using python 3.11
I installed both taskiq and taskiq-redis modules.
Thanks for making this library, it looks really promising.

**Comment by s3rius** [comment]
Hi, @Emilianocm23, and thanks for raising this issue. I guess the problem is that result is not ready yet. 

I agree that the error is not obvious. We should definitely change it. 

To solve this issue, you can use [wait_result](https://github.com/taskiq-python/taskiq/blob/88dbe3aec51bba891924e428c8142ee057bb8791/taskiq/task.py#L46). It will wait for the result to be ready.

**Comment by booqoffsky** [comment]
@Emilianocm23 
In addition, such an error may appear if taskiq workers were not initially started. Just in case, here is how to run the workers: https://taskiq-python.github.io/guide/cli.html#worker

For your example, if the code file is called `mycode.py`, just run the command:
`taskiq worker mycode:broker`

**Comment by sminnee** [comment]
FWIW it looks like this issue can be closed.
