### ISSUE TITLE
support redis 5.0.0

### ISSUE THREAD

**Issue by lpdswing** [taskiq-python/taskiq-redis#41]
poetry add taskiq-redis

Because taskiq-redis (0.4.0) depends on redis (>=4.2.0,<5.0.0)
 and redis (5.0.0) depends on redis (5.0.0), taskiq-redis (0.4.0) is incompatible with redis (5.0.0).
And because no versions of redis match >5.0.0,<6.0.0, taskiq-redis (0.4.0) is incompatible with redis (>=5.0.0,<6.0.0).
So, because app depends on both redis (^5.0.0) and taskiq-redis (0.4.0), version solving failed.

**Comment by s3rius** [comment]
Closed as completed.
