### ISSUE TITLE
Custom serializers

### ISSUE THREAD

**Issue by quizmoon** [taskiq-python/taskiq-redis#56]
Would be great to have custom serializers in set/get results, or at least JSON, like it is implemented in the main project TaskIQ.

**Comment by s3rius** [comment]
Look, I've checked the code and you can do so. You can set custom serializers in the constructor.

**Comment by quizmoon** [comment]
@s3rius , in the backend part it is hardcoded, e.g in "set_result":

```
        redis_set_params: Dict[str, Union[str, bytes, int]] = {
            "name": task_id,
            "value": **pickle.dumps(result)**,
        }
```

**Comment by s3rius** [comment]
I see now. Accidentally skipped it. We will add a new parameter to the constructor.
